### ISSUE TITLE
Create LifeCycle Regression Tests

### ISSUE THREAD

**Issue by am-webdev** [am-webdev/broker-models#1]
**Background**
Create LifeCycle Regression Tests 

**Tasks**
- Create LifeCylce Tests (see TODO within PersonEntityTest line 189)
   - Bid
   - Person
   - Auction

**Definition of Done**
LifeCycle tests are implemented

**Comment by am-webdev** [comment]
LifeCylce tests analog zu PersonEntityTest erweitern für:

- [ ] Auction
- [ ] Bid

**Comment by TheYashasama** [comment]
Martin und ich haben die LifeCycle Tests fertig gemacht
